name: CI for MLflow Project

on:
  push:
    branches:
      - main  # Workflow ini dijalankan saat ada push ke main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Gunakan ubuntu untuk menjalankan workflow

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout repository ke runner

    # Step untuk Setup Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v1
      with:
        conda-version: "4.10.3"  # Bisa coba versi yang lebih stabil
        python-version: "3.8"  # Sesuaikan dengan versi Python yang dibutuhkan
        environment-file: MLProject/conda.yaml  # Pastikan file conda.yaml ada di repo

    # Step untuk Membuat Environment dari conda.yaml
    - name: Create conda environment from conda.yaml
      run: |
        conda env create -f MLProject/conda.yaml  # Membuat environment berdasarkan conda.yaml
        conda activate mlflow-project  # Mengaktifkan environment mlflow-project

    # Step untuk Menjalankan MLflow
    - name: Run MLflow experiment
      run: |
        conda activate mlflow-project  # Pastikan environment aktif
        mlflow run . --experiment-name mlflow-experiment

    - name: Debugging - Check conda info
      run: |
        echo $PATH
        conda info
        conda list
        which conda

